#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Nomad
  hosts: Ubuntu
  become: True
  tasks:
    - name: Unpack Nomad Archive
      unarchive: src=https://releases.hashicorp.com/nomad/0.3.0/nomad_0.3.0_linux_amd64.zip dest=/usr/local/bin copy=no creates=/usr/local/bin/nomad mode=0555
    - name: Echo Nomad version
      command: nomad --version
